import '@/app/globals.css'
import Footer from '@/components/layouts/Footer'
import Header from '@/components/layouts/Header'
import { Zen_Kaku_Gothic_New } from 'next/font/google'

const zenkakuGothicNew = Zen_Kaku_Gothic_New({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Animecca',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={`${zenkakuGothicNew.className} w-full bg-blue-300`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
